version: "3"

services: 
  nginx:
    container_name: container-nginx
    image: joaofelippe/unialfa-nginx
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./html:/usr/share/nginx/html